[features]
seeds = false
skip-lint = false
[programs.localnet]
lesson = "8N7hQRBWZJnjMW1U6kutDKCRd4BRGtBpaBr7v9i59iLp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
