[features]
seeds = false
skip-lint = false
[programs.localnet]
lesson = "2MH7qg3Ga1YxjDHX916qRnKzwpX1sxqVpTbKB1h7jmfQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
